import comp from "D:/Codes/tutorial-vuepress-hope/src/.vuepress/.temp/pages/blog/python/how-selenium.html.vue"
const data = JSON.parse("{\"path\":\"/blog/python/how-selenium.html\",\"title\":\"Python使用Selenium详细步骤\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Python使用Selenium详细步骤\",\"icon\":\"devicon:selenium\",\"head\":[[\"meta\",{\"name\":\"keywords\",\"content\":\"python selenium\"}],[\"meta\",{\"name\":\"description\",\"content\":\"Python使用Selenium的详细步骤\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.igoblogs.com/blog/python/how-selenium.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"一起来编程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Python使用Selenium详细步骤\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Selenium介绍 Selenium官方中文文档：https://www.selenium.dev/zh-cn/documentation/ Selenium 可以直接在浏览器上操作，像人一样进行文本框输入内容、按钮点击、链接弹出、下拉等操作，一般我们用它来做自动化测试。 它在爬虫领域利用也非常广泛，能解决大部分网页反爬问题，Selenium可以根据...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://www.igoblogs.com/images/python/selenium/01-install-start.png \\\"开始安装Selenium\\\"\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"python\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"selenium\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-10-21T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Python使用Selenium详细步骤\\\",\\\"image\\\":[\\\"https://www.igoblogs.com/images/python/selenium/01-install-start.png \\\\\\\"开始安装Selenium\\\\\\\"\\\",\\\"https://www.igoblogs.com/images/python/selenium/01-install-finish.png \\\\\\\"安装完成Selenium\\\\\\\"\\\"],\\\"datePublished\\\":\\\"2024-10-21T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"小钟同学\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]],\"category\":[\"Python\"],\"tags\":[\"python\",\"selenium\"],\"date\":\"2024-10-21T00:00:00.000Z\",\"permalink\":\"/blog/python/how-selenium.html\",\"excerpt\":\"1.Selenium介绍<br>2.Selenium环境搭建\",\"description\":\"Selenium介绍 Selenium官方中文文档：https://www.selenium.dev/zh-cn/documentation/ Selenium 可以直接在浏览器上操作，像人一样进行文本框输入内容、按钮点击、链接弹出、下拉等操作，一般我们用它来做自动化测试。 它在爬虫领域利用也非常广泛，能解决大部分网页反爬问题，Selenium可以根据...\",\"gitInclude\":[]},\"headers\":[{\"level\":2,\"title\":\"Selenium介绍\",\"slug\":\"selenium介绍\",\"link\":\"#selenium介绍\",\"children\":[]},{\"level\":2,\"title\":\"Selenium环境搭建\",\"slug\":\"selenium环境搭建\",\"link\":\"#selenium环境搭建\",\"children\":[]},{\"level\":2,\"title\":\"安装驱动WebDriver\",\"slug\":\"安装驱动webdriver\",\"link\":\"#安装驱动webdriver\",\"children\":[]}],\"readingTime\":{\"minutes\":3.13,\"words\":938},\"filePathRelative\":\"blogs/1.python/20241123-how-selenium.md\",\"localizedDate\":\"2024年10月21日\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
