import comp from "D:/Codes/tutorial-vuepress-hope/src/.vuepress/.temp/pages/notes/python/syntax/data-type/str.html.vue"
const data = JSON.parse("{\"path\":\"/notes/python/syntax/data-type/str.html\",\"title\":\"字符串\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"字符串\",\"createTime\":\"2024/10/27 20:47:19\",\"permalink\":\"/notes/python/syntax/data-type/str.html\",\"article\":false,\"description\":\"创建字符串 Python 中的字符串可以是由 单引号（'），双引号（\\\"）、三单引号（'''）或三双引号（\\\"\\\"\\\"）包围。 注：以下例子中，都使用推荐的双引号 ::: demo-wrapper title=\\\"运行结果\\\" File not found ::: 字符串运算 ::: demo-wrapper title=\\\"运行结果\\\" File not found...\",\"gitInclude\":[\"../../demo/var-str-create-result.md\",\"../../demo/var-str-operator-result.md\",\"../../demo/var-str-format-result.md\",\"../../demo/var-str-funcuse-result.md\"],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://www.igoblogs.com/notes/python/syntax/data-type/str.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"一起来编程\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"字符串\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"创建字符串 Python 中的字符串可以是由 单引号（'），双引号（\\\"）、三单引号（'''）或三双引号（\\\"\\\"\\\"）包围。 注：以下例子中，都使用推荐的双引号 ::: demo-wrapper title=\\\"运行结果\\\" File not found ::: 字符串运算 ::: demo-wrapper title=\\\"运行结果\\\" File not found...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"字符串\\\",\\\"description\\\":\\\"创建字符串 Python 中的字符串可以是由 单引号（'），双引号（\\\\\\\"）、三单引号（'''）或三双引号（\\\\\\\"\\\\\\\"\\\\\\\"）包围。 注：以下例子中，都使用推荐的双引号 ::: demo-wrapper title=\\\\\\\"运行结果\\\\\\\" File not found ::: 字符串运算 ::: demo-wrapper title=\\\\\\\"运行结果\\\\\\\" File not found...\\\"}\"]]},\"headers\":[{\"level\":2,\"title\":\"创建字符串\",\"slug\":\"创建字符串\",\"link\":\"#创建字符串\",\"children\":[]},{\"level\":2,\"title\":\"字符串运算\",\"slug\":\"字符串运算\",\"link\":\"#字符串运算\",\"children\":[]},{\"level\":2,\"title\":\"格式化\",\"slug\":\"格式化\",\"link\":\"#格式化\",\"children\":[]},{\"level\":2,\"title\":\"常见函数\",\"slug\":\"常见函数\",\"link\":\"#常见函数\",\"children\":[]},{\"level\":2,\"title\":\"常用功能\",\"slug\":\"常用功能\",\"link\":\"#常用功能\",\"children\":[{\"level\":3,\"title\":\"大小写转换\",\"slug\":\"大小写转换\",\"link\":\"#大小写转换\",\"children\":[]},{\"level\":3,\"title\":\"连接与重复\",\"slug\":\"连接与重复\",\"link\":\"#连接与重复\",\"children\":[]}]}],\"readingTime\":{\"minutes\":0.73,\"words\":220},\"filePathRelative\":\"notes/python/syntax/data-types/str.md\",\"excerpt\":\"<h2>创建字符串</h2>\\n<p>Python 中的字符串可以是由   单引号（'），双引号（\\\"）、三单引号（'''）或三双引号（\\\"\\\"\\\"）包围。</p>\\n<p><strong>注：以下例子中，都使用推荐的双引号</strong></p>\\n<!-- @[code{12-}](../../demo/var-str-create.py) -->\\n<p>::: demo-wrapper title=\\\"运行结果\\\"</p>\\n<p>File not found</p>\\n<p>:::</p>\\n<h2>字符串运算</h2>\\n<!-- @[code{12-}](../../demo/var-str-operator.py) -->\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
